<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="53.099" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2023-11-01T06:32:57" tests="0" file="cypress\e2e\ananda\RHEA.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="RHEA Application" timestamp="2023-11-01T06:32:57" tests="1" time="53.096" failures="1">
    <testcase name="RHEA Application verifies the title" time="0.000" classname="verifies the title">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; Cannot read properties of undefined (reading &apos;getHasFocus&apos;)

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application" type="TypeError"><![CDATA[TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read properties of undefined (reading 'getHasFocus')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
    at Context.eval (webpack://cypress-junit-azure-devops/./cypress/e2e/ananda/RHEA.cy.js:18:9)]]></failure>
    </testcase>
  </testsuite>
</testsuites>